version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: code_review
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./backend-application
    container_name: code-analyzer-backend
    depends_on:
      - postgres
      - minio
      - ollama
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  ollama_data: